name = "icanhazutc"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[build.upload]
format = "modules"

[[rules]]
type = "Text"
globs = ["**/*.html"]

[env.production]
name = "icanhazutc"
