name = "icanhazutc"
main = "dist/worker.js"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[[rules]]
type = "Text"
globs = ["*.html"]
fallthrough = false

[env.production]
name = "icanhazutc"
